### ISSUE TITLE
Implement community page designs

### ISSUE THREAD

**Issue by seanperkins** [NYCEDU/nycedu-react#10]

**Comment by HeyCat** [comment]
![deborah professional profile picture](https://cloud.githubusercontent.com/assets/5464910/20489236/dfadd276-afd7-11e6-9751-c05aa7e2329d.jpg)
![eugene](https://cloud.githubusercontent.com/assets/5464910/20489414/9006c2a4-afd8-11e6-89c0-f49a318b33d4.png)

**Comment by HeyCat** [comment]
- [x] add a border around sign up box to separate that div within the page (currently looks like it's floating)
- [x] h1s that mostly serve as page titles: Roboto bold, light green #8BC34A, size 28pt. 
- [ ] When sign up modal pops up, the position of background jumps.

**Comment by rickymetz** [comment]
>When sign up modal pops up, the position of background jumps.

This is because the modal locks the background (aka removes the scrollbar) to prevent unintentional scrolling on the background page element. This quirk is only visible on Mac OS browers, linux and windows users are unaffected.
To "Fix" this would mean permanently making the scroll bars visible on the pages (which would only be seen by mac users, since permanent scroll bars are already canon in windows and linux), is this something you want to do @HeyCat?
